version: "3.8"

services:
  fe-xyzone:
    image: fe-xyzone
    container_name: fe-xyzone
    build: .
    env_file:
      - .env
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    restart: always
